const $=s=>document.querySelector(s);let stream=null,track=null,mode="landscape",timer=0;
const video=$("#video"),original=$("#original"),pro=$("#pro"),canvas=$("#canvas");
const P={landscape:{f:"environment",w:3840,h:2160,name:"LANDSCAPE",text:"Max resolution · focus · stability"},portrait:{f:"environment",w:3024,h:4032,name:"PORTRAIT",text:"High resolution · face focus · stability"},selfie:{f:"user",w:1920,h:1080,name:"SELFIE",text:"Front camera · focus · natural exposure"}};
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
async function start(){if(stream)stream.getTracks().forEach(t=>t.stop());let p=P[mode];try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:p.f},width:{ideal:p.w},height:{ideal:p.h}}});video.srcObject=stream;original.srcObject=stream;pro.srcObject=stream;track=stream.getVideoTracks()[0];let s=track.getSettings(),c=track.getCapabilities?.()||{};$("#res").textContent=(s.width||"?")+"×"+(s.height||"?");$("#lens").textContent=s.facingMode==="user"?"FRONT":"BACK";$("#scene").textContent=p.name;$("#protext").textContent=p.text;if(c.focusMode?.includes("continuous"))try{await track.applyConstraints({advanced:[{focusMode:"continuous"}]})}catch{}if(c.zoom){$("#zoom").max=Math.min(8,c.zoom.max);$("#zoom").value=1}toast("PRO AUTO actief")}catch{toast("Geef camera-toegang")} }
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x===b));start()});
$("#flip").onclick=()=>{mode=mode==="selfie"?"landscape":"selfie";document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));start()};
$("#capture").onclick=async()=>{if(!video.videoWidth)return;if(timer){toast("Foto over "+timer+"s");await new Promise(r=>setTimeout(r,timer*1000))}canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d").drawImage(video,0,0,canvas.width,canvas.height);let d=canvas.toDataURL("image/jpeg",.96);let a=document.createElement("a");a.href=d;a.download="PhotoPro-"+Date.now()+".jpg";let img=new Image();img.src=d;img.alt="Foto";a.appendChild(img);$("#shots").prepend(a);toast("Pro-foto gemaakt")};
$("#advanced").onclick=()=>$("#panel").classList.toggle("hidden");$("#close").onclick=()=>$("#panel").classList.add("hidden");
$("#ev").oninput=async e=>{let v=+e.target.value;$("#evout").textContent=(v>0?"+":"")+v.toFixed(1);$("#evmini").textContent="EV "+v.toFixed(1);try{await track?.applyConstraints({advanced:[{exposureCompensation:v}]})}catch{}};
$("#zoom").oninput=async e=>{let z=+e.target.value;$("#zoomout").textContent=z.toFixed(1)+"×";try{await track?.applyConstraints({advanced:[{zoom:z}]})}catch{}};
$("#hdr").onclick=()=>toast("HDR Auto geselecteerd");$("#exposure").onclick=()=>$("#panel").classList.remove("hidden");
$("#timer").onclick=()=>{timer=timer===0?3:timer===3?10:0;$("#timer b").textContent=timer?timer+"s":"OFF"};
$("#flash").onclick=()=>toast("Flits Auto");window.addEventListener("beforeinstallprompt",e=>{$("#install").hidden=false;window._p=e});$("#install").onclick=()=>window._p?.prompt();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");start();