const $=s=>document.querySelector(s),video=$("#video");let stream=null,track=null,mode="landscape",look=0,timer=0;
const P={landscape:{f:"environment",w:3840,h:2160,n:"LANDSCHAP",b:[1.035,1.045,1.01]},portrait:{f:"environment",w:3024,h:4032,n:"PORTRET",b:[1.018,1.025,1.015]},selfie:{f:"user",w:1920,h:1080,n:"SELFIE",b:[1.012,1.015,1.018]}};
const L=[["Natural",1,1,1,0],["Vivid",1.045,1.105,1.015,.01],["Cinematic",1.085,.925,.985,-.01],["Golden",1.025,1.035,1.015,.055],["Cool",1.025,.985,1.015,-.045],["Noir",1.16,.02,1,0],["Matte",.91,.86,1.01,.015],["Sunset",1.035,1.085,1.02,.065],["Forest",1.045,1.085,1,.012],["Portrait",1.015,.975,1.012,.025]];
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1600)}
async function start(){if(stream)stream.getTracks().forEach(t=>t.stop());let p=P[mode];try{stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:p.f},width:{ideal:p.w},height:{ideal:p.h}}});video.srcObject=stream;track=stream.getVideoTracks()[0];let s=track.getSettings(),c=track.getCapabilities?.()||{};$("#resolution").textContent=(s.width||"?")+"×"+(s.height||"?");$("#scene").textContent=p.n;if(c.focusMode?.includes("continuous"))try{await track.applyConstraints({advanced:[{focusMode:"continuous"}]})}catch{}if(c.zoom)$("#zoom").max=Math.min(8,c.zoom.max);$("#state").textContent="READY"}catch{$("#state").textContent="CAMERA ERROR";toast("Geef camera-toegang")}}
function thumbs(){let w=$("#filters");L.forEach((a,i)=>{let b=document.createElement("button");b.className="filter"+(i===0?" active":"");b.innerHTML=`<canvas></canvas>${a[0]}`;let c=b.querySelector("canvas"),x=c.getContext("2d");c.width=124;c.height=84;let g=x.createLinearGradient(0,0,124,84);g.addColorStop(0,"#66717e");g.addColorStop(.55,"#b89b76");g.addColorStop(1,"#28313c");x.fillStyle=g;x.fillRect(0,0,124,84);x.fillStyle="rgba(255,255,255,.55)";x.beginPath();x.arc(65,42,21,0,7);x.fill();if(a[0]==="Noir"){x.fillStyle="#111";x.globalAlpha=.5;x.fillRect(0,0,124,84);x.globalAlpha=1}b.onclick=()=>{look=i;document.querySelectorAll(".filter").forEach(q=>q.classList.remove("active"));b.classList.add("active");$("#selected").textContent=a[0].toUpperCase()};w.appendChild(b)})}
function enhance(src){let [_,co,sa,br,temp]=L[look],base=P[mode].b;co*=base[0];sa*=base[1];br*=base[2];let o=document.createElement("canvas");o.width=src.width;o.height=src.height;let x=o.getContext("2d",{willReadFrequently:true});x.drawImage(src,0,0);let im=x.getImageData(0,0,o.width,o.height),d=im.data;
for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2],lum=.2126*r+.7152*g+.0722*b,sh=Math.max(0,(120-lum)/120),hi=Math.max(0,(lum-165)/90),t=1+(co-1)*(1-.38*sh);r=(r-128)*t+128+sh*2.7-hi*2.3;g=(g-128)*t+128+sh*2.1-hi*2;b=(b-128)*t+128+sh*1.6-hi*2;let m=(r+g+b)/3;r=m+(r-m)*sa;g=m+(g-m)*sa;b=m+(b-m)*sa;r*=br+temp*.1;g*=br;b*=br-temp*.07;d[i]=Math.max(0,Math.min(255,r));d[i+1]=Math.max(0,Math.min(255,g));d[i+2]=Math.max(0,Math.min(255,b))}x.putImageData(im,0,0);return o.toDataURL("image/jpeg",.97)}
async function capture(){if(!video.videoWidth)return;if(timer){toast("Foto over "+timer+"s");await new Promise(r=>setTimeout(r,timer*1000))}$("#state").textContent="PROCESSING";let c=document.createElement("canvas");c.width=video.videoWidth;c.height=video.videoHeight;c.getContext("2d").drawImage(video,0,0);let data=enhance(c);let a=document.createElement("a");a.href=data;a.download=`PhotoPro-${P[mode].n}-${Date.now()}.jpg`;document.body.appendChild(a);a.click();a.remove();$("#state").textContent="SAVED";toast("✓ Foto opgeslagen");setTimeout(()=>$("#state").textContent="READY",1400)}
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x===b));start()});
$("#flip").onclick=()=>{mode=mode==="selfie"?"landscape":"selfie";document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x.dataset.mode===mode));start()};
$("#capture").onclick=capture;$("#settings").onclick=()=>$("#panel").classList.toggle("hiddenPanel");$("#evBtn").onclick=()=>$("#panel").classList.toggle("hiddenPanel");$("#hdr").onclick=()=>toast("SMART HDR");$("#timer").onclick=()=>{timer=timer===0?3:timer===3?10:0;$("#timer b").textContent=timer?timer+"s":"OFF"};
$("#ev").oninput=async e=>{let v=+e.target.value;$("#evOut").textContent=(v>0?"+":"")+v.toFixed(1);$("#evMini").textContent="EV "+v.toFixed(1);try{await track?.applyConstraints({advanced:[{exposureCompensation:v}]})}catch{}};
$("#zoom").oninput=async e=>{let z=+e.target.value;$("#zoomOut").textContent=z.toFixed(1)+"×";$("#zoomMini").textContent=z.toFixed(1)+"×";try{await track?.applyConstraints({advanced:[{zoom:z}]})}catch{}};
thumbs();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");start();